name: MSBuild

on:
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'

    - name: Build
      run: |
       qmake build.pro
       make]
       ls
