name: MSBuild

on:
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
       qmake build.pro
       make]
       ls
